// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251215100710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BotStrategy", b =>
                {
                    b.Property<int>("BotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BotId"));

                    b.Property<int>("MoneyLimit")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.Property<bool>("Start")
                        .HasColumnType("bit")
                        .HasColumnName("start");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strategy");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BotId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("bot_strat", (string)null);
                });

            modelBuilder.Entity("GameData", b =>
                {
                    b.Property<int>("GDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GDataId"));

                    b.Property<int>("CoopCoop")
                        .HasColumnType("int")
                        .HasColumnName("coopcoop");

                    b.Property<int>("CoopDeflect")
                        .HasColumnType("int")
                        .HasColumnName("coopdeflect");

                    b.Property<int>("DeflectCoop")
                        .HasColumnType("int")
                        .HasColumnName("deflectcoop");

                    b.Property<int>("DeflectDeflect")
                        .HasColumnType("int")
                        .HasColumnName("deflectdeflect");

                    b.Property<int>("MoneyPoints")
                        .HasColumnType("int")
                        .HasColumnName("m_points");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GDataId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("game_data", (string)null);
                });

            modelBuilder.Entity("GameSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Choice1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("choice_type");

                    b.Property<string>("Choice2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("choice_type2");

                    b.Property<int>("CoopCoop1")
                        .HasColumnType("int")
                        .HasColumnName("coopcoop");

                    b.Property<int>("CoopCoop2")
                        .HasColumnType("int")
                        .HasColumnName("coopcoop2");

                    b.Property<int>("CoopDeflect1")
                        .HasColumnType("int")
                        .HasColumnName("coopdeflect");

                    b.Property<int>("CoopDeflect2")
                        .HasColumnType("int")
                        .HasColumnName("coopdeflect2");

                    b.Property<int>("DeflectCoop1")
                        .HasColumnType("int")
                        .HasColumnName("deflectcoop");

                    b.Property<int>("DeflectCoop2")
                        .HasColumnType("int")
                        .HasColumnName("deflectcoop2");

                    b.Property<int>("DeflectDeflect1")
                        .HasColumnType("int")
                        .HasColumnName("deflectdeflect");

                    b.Property<int>("DeflectDeflect2")
                        .HasColumnType("int")
                        .HasColumnName("deflectdeflect2");

                    b.Property<int>("GameNr1")
                        .HasColumnType("int")
                        .HasColumnName("game_nr");

                    b.Property<int>("GameNr2")
                        .HasColumnType("int")
                        .HasColumnName("game2_nr");

                    b.Property<int>("MoneyPoints1")
                        .HasColumnType("int")
                        .HasColumnName("m_points");

                    b.Property<int>("MoneyPoints2")
                        .HasColumnType("int")
                        .HasColumnName("m_points2");

                    b.Property<int>("User1")
                        .HasColumnType("int")
                        .HasColumnName("user1_id");

                    b.Property<int>("User2")
                        .HasColumnType("int")
                        .HasColumnName("user2_id");

                    b.HasKey("ID");

                    b.HasIndex("User1");

                    b.HasIndex("User2");

                    b.ToTable("game_session", (string)null);
                });

            modelBuilder.Entity("PendingInteraction", b =>
                {
                    b.Property<int>("PendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pending_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PendingId"));

                    b.Property<string>("TargetChoice")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_choice");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.Property<string>("UserChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_choice");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PendingId");

                    b.HasIndex("TargetId");

                    b.HasIndex("UserId");

                    b.ToTable("pending_interactions", (string)null);
                });

            modelBuilder.Entity("UserData", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("GameNr")
                        .HasColumnType("int")
                        .HasColumnName("game_nr");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("int")
                        .HasColumnName("nr_turns");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("user_data", (string)null);
                });

            modelBuilder.Entity("BotStrategy", b =>
                {
                    b.HasOne("UserData", "UserData")
                        .WithOne("BotStrategy")
                        .HasForeignKey("BotStrategy", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("GameData", b =>
                {
                    b.HasOne("UserData", "UserData")
                        .WithOne("GameData")
                        .HasForeignKey("GameData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("GameSession", b =>
                {
                    b.HasOne("UserData", "User1Nav")
                        .WithMany()
                        .HasForeignKey("User1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserData", "User2Nav")
                        .WithMany()
                        .HasForeignKey("User2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1Nav");

                    b.Navigation("User2Nav");
                });

            modelBuilder.Entity("PendingInteraction", b =>
                {
                    b.HasOne("UserData", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserData", b =>
                {
                    b.Navigation("BotStrategy");

                    b.Navigation("GameData");
                });
#pragma warning restore 612, 618
        }
    }
}
